config.h

Looks like the value on the defaultbg=256 gives a segmentation fault
```
carlos@Sirio:~/src/st/st_LukeSmithxyz$ ./st 
*** Error in `./st': free(): invalid next size (normal): 0x00000000010d6a10 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f41962587e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f419626137a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f419626553c]
/lib/x86_64-linux-gnu/libc.so.6(_IO_setb+0x4b)[0x7f419625c54b]
/lib/x86_64-linux-gnu/libc.so.6(_IO_file_close_it+0xae)[0x7f419625a8ee]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x18f)[0x7f419624e3ef]
/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x4ed2a)[0x7f4196e5ed2a]
/usr/lib/x86_64-linux-gnu/libX11.so.6(_XlcFileName+0x114)[0x7f4196e5f114]
/usr/lib/x86_64-linux-gnu/libX11.so.6(_XimCheckIfLocalProcessi …
```

fix defaultbg value, solve sigfault

---

config.h

With the gruvbox update defaultfg and default cursors were left at Solarized's values, leaving default text a sickly blue. See [gruvbox st port](https://github.com/morhetz/gruvbox-contrib/blob/master/st/gruvbox-dark.h).
Also, the lines just after 105 were previously ignored since they counted as colors 16 and 17 instead of 256 and 257 (see x.c line 736). New line 105 gives them back their intended index values. While these lines can now be used, they're not at the moment, so they could just be deleted as well.
When no longer ignored, "brwhite" caused errors (not an accepted color name), so changed.

Correct gruvbox defaultfg and cursor colors

---

README.md

If this was supposed to read solarized instead of colorized, maybe change to gruvbox as well:
> This build will use colorized colors by default and as a fallback.

corrects color and font size info

---

config.h

Tested by adding `*border` on my `.Xresources` file. Reran `xrdb ~/.Xresources`. Ran `st`. Border changed as expected.
Maybe consider naming internalBorder to match how URxvt treats it and for better accuracy. Initially didn't simply because it would ruin the entire style of the array initialization (I know a bit silly).

Added Xresource border to adjust the internal border.

---

config.mk

This will allow people to assign a different `PREFIX` value without having to modify `config.mk` manually.
For example, under `fish`:
env PREFIX= DESTDIR=~/.local/bin make install

Use conditional variable assignment for PREFIX

---

config.h

Noticed a problem with mutt and newsboat where some links which have `&` in them wasn't displayed right, thus not opening the right link.
Example:
`http://www.phoronix.com/scan.php?page=news_item&px=GCC-9.1-Compiler-Released`
would be seen/opened as :
`http://www.phoronix.com/scan.php?page=news_item`
so, anything in URL after `&` was omitted.
This commit should correct this.

include links with & in URLs

---

.Xdefaults
Makefile
PKGBUILD
README.md
config.h
config.mk
st.1
st.c
st.h
win.h
x.c

Updated to latest git (20190414.f1546cf) & updated patches.
Changes:
- Upstream fixes.
- Alpha: Opacity value is now typed in float (0-1).
Also "-A" cmd option added as alternative opacity changing method.
- Clipboard: middle click pastes from clipboard.
- Organized shortcuts.

Updated st to 0.8.2

---

PKGBUILD

I think not hardcoding the package version is better idea. Since there is no tags in this repository, I used awk to get version from config.mk. I will notify AUR maintainer if this is ok.

get version from config.mk

---

config.h
refresh.sh

The cursorColor references colorname[258] element but this is not declared in the definition.  This pull request updates the colorname declaration with a 258th element.
Symptoms are: #71  and also other weird behaviour - I'm surprised the current version works for people?  Maybe it's because I actually have the `*.cursorColor:  #add8e6` defined in my .Xresources.
(Note - it also includes defining the default bg and foreground colors to 256 and 257 which for some reason weren't set correctly?  + my own "refresh" script for rebuilding)

correct colorname declaration

---

config.h

I wanted to copy the link **http://172.17.0.5:6006**
but it picked up the following **http://172.17.0.5**
The modification I made only makes sure that there's none or one colon. 
It will accept links with port ranges such as **http://172.17.0.5:600645789084**
The regex for port ranges is too complicated so I think It's better not to include it for simplicity's sake.

Include links with port numbers

---

config.h

The default gruvbox has a typical base of 16 colours, other themes have might have a seperate background, foreground and cursor colour.  With the defaultfg, defaultbg, defaultcs set to 15,0 and 15 respectively any definitions for foreground background and cursor colour in .Xresources will not be applied.
The update to config sets the default fg,bg and cs to 257,256 and 258 consistent with the .Xresources resource declaration later in the config but also retains the gruvbox default theme colours.
All the best
Rob

default fg, bg and cursor - modified so works with .Xresources

---

x.c

Most composite managers uses [premultiplied RGB](https://en.wikipedia.org/wiki/Alpha_compositing) color when alpha blending. 
The [st-alpha-0.8.2.diff](https://st.suckless.org/patches/alpha/st-alpha-0.8.2.diff) doesn't contain the premultiplication fix present in the [st-alpha-20190116-3be4cf1.diff](https://st.suckless.org/patches/alpha/st-alpha-20190116-3be4cf1.diff). 
In this PR I reimplemented the premultiplication using the new float alpha parameter maintaining the 8-bit padded ushort for each channel.

Premultiply background RGB values if alpha is used

---

README.md
config.h
x.c

This should fix #93. @w3bb could you please confirm that it works for you?
On a side note I'm not sure whether we really need this. `st` is supposed to use `fontconfig`'s fallback, isn't it?

Apply font2 patch

---

config.h

Hi,
I noticed your addition of the font2 patch recently.
Short story:
I've modified the resources array to take an item for the font2 array.
Long story:
I switch between laptop and monitors regularly which have different resolutions.  A bit of scripting and some variables in my Xresources help with the switching resolutions.  Having the Xresources patch is in st makes this a breeze.  The addition of font2 made this incompatible but it's pretty simple to add this into the reources array. For interest my Xresources is below:
https://gist.github.com/rjl6789/115d5494406d82060b0ec592151639dd
Cheers
Rob

additional Xresources item compatible with font2 patch

---

st-copyout

I've a prompt which starts with a space and looks like this:
` undx@rogue  ~/Code/local/st  ➦ bf29538 `
` ✘ undx@rogue  ~ `
Maybe I'm not the only one in that case...

fix prompt starting with space(s)

---

st-copyout

Realized that awk was slurping too much data when prompts starts with a space.
As `esp1` may be stripped, the pattern may not be found (`^$esp`) and goes to end of output.
This may add space(s) to the end to output.

fix excessive slurping when prompt starts w/ space(s)

---

.Xdefaults

You might want to update every theme with different colors - I just didn't knew which ones to put there
(or maybe just mimic `color0` as `background` & `color15` as `foreground` and `cursorColor` (see the diff @ #108))
~~Fixes #108; fixes #97~~
There are apparently some issues with [`pywal`](https://github.com/dylanaraps/pywal/wiki/Getting-Started), see https://github.com/LukeSmithxyz/st/issues/108#issuecomment-506974909

Add background, foreground, cursor color example

---

config.h

Hi @LukeSmithxyz
This change enables hash-based urls support for openurl and copyurl commands.
It fixes this issue #119

Add hash symbol in openurlcmd and copyurlcmd regexp

---

config.h
st.c
st.h

This patch adds a configuration tweak to adjust how often `xximspot` function is called.
The call to `xximspot` can cause tremendous terminal slowdowns under certain conditions. This patch fixes the problem by only calling this function periodically.

Add interval timer to XIM spot updates

---

x.c

This behaviour was introduced in https://github.com/LukeSmithxyz/st/commit/683341140065b3096ee9e7e3e3b042f9c52230a6
Resolves: #177

Do not copy text to clipboard after selecting

---

st-copyout

The first grep in the original script will return "binary file matches" if there are NUL characters in PS1, e.g, emojis.
The added line gets rid of NUL characters.

Get rid of NUL character in PS1

---

config.h
st.c
st.h
win.h
x.c

Added OSC patch ( https://st.suckless.org/patches/osc_10_11_12/ ) which allows for changing the background, foreground, and cursor color on the fly using OSC escape codes 10, 11 and 12. I also made a small change in x.c to preserve the background transparency after changing the colors. This fixes all the issues I've had using pywal with st.

Pywal live reload with OSC patch and transparency fix

---

st.h
x.c

Closes #223 
I couldn't find any edge-cases, although some extra testing will never hurt.

Glyph truncation fix

---

config.h
st.c
st.h
x.c

Based on https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20190131-e23acb9.diff. Makes scrolling just werk, mouse wheel only, whether in shell or pager.

Make mouse scroll emit ^E^Y only in alt screen, normal scrolling otherwise

---

config.h

I modified `*copyurlcmd[]` to recognize gopher, gemini, ftp, ftps, and git url schemes, and fixed a bug where urls containing a tilde were not fully recognized.

Expanded url scheme support and fixed issue with tilde in url

---

st-urlhandler

Urls lile:
https://whatever.domain/~myprecious/usefull-blog.html
https://brb.imback.maybe/isit/blah#sure
Were not propery handled (everything after either '#' or '\~' were ignored).
Escaped '#' and added '\~' in the regex.
Signed-off-by: Pierguido Lambri <plambri@redhat.com>

Fixed a small issue with the urlhandler.

---

Xdefaults
config.h
st.c
st.h
x.c

Solves #295
This is a somewhat adapted version of [suckless_alpha_focus](https://st.suckless.org/patches/alpha_focus_highlight/) for this build of st

Add support for additional alpha when the term-window is not focused

---

README.md

Outdated information. Currently scrollback patch is used instead.

Remove scroll info from README.md

---

hb.c

Using FEATURE macro and the corresponding method  from @cog1to latest patch.
Tested on **Fira Code** font.
Enable/disable the feature within this file, and then `sudo make install` as usual.

Add stylistic sets / open type font feature

---

x.c

kpress function in x.c previously relied on the wrong understanding
of XmbLookupString behavior. When the composed string is longer
than the available buffer, the buffer is not initialized and the
actual length of the data available to read is returned, not
the amount of data written. When that amount is later used to
process the contents of this buffer, not only will the random
contents of the uninitialized buffer be sent directly to the
terminal and whichever application is now running in it, but
possibly also whatever is in the memory after that buffer,
leading to undefined behavior and possible random command execution.

Fix buffer overflow in input handling
